import base64
import time
import webbrowser



encoded_code = b'aW1wb3J0IHRpbWUKaW1wb3J0IHdlYmJyb3dzZXIKZGVmIGNoYXRib3QoKToKICBwcmludCgiSGVsbG8hIEknbSBSYXlnbyBpbXAgYWkuIEhvdyBjYW4gSSBoZWxwIHlvdT8iKQogIHdoaWxlIFRydWU6CiAgICB1c2VyX2lucHV0ID0gaW5wdXQoIj4gIikubG93ZXIoKQogICAgaWYgImhlbGxvIiBpbiB1c2VyX2lucHV0IG9yICJoaSIgaW4gdXNlcl9pbnB1dDoKICAgICAgcHJpbnQoIkhlbGxvIHRoZXJlISIpCiAgICBlbGlmICJob3cgYXJlIHlvdSIgaW4gdXNlcl9pbnB1dDoKICAgICAgcHJpbnQoIkknbSBkb2luZyB3ZWxsLCB0aGFua3MgZm9yIGFza2luZyEhIikKICAgIGVsaWYgIndoYXQncyB5b3VyIG5hbWUiIGluIHVzZXJfaW5wdXQ6CiAgICAgIHByaW50KCJteSBuYW1lIGlzIFJheWdvIGltcCBhaSBidXQgaSBsaWtlIHRvIGJlIGNhbGxlZCBSb2JlcnQiKQogICAgZWxpZiAid2hhdCBjYW4geW91IGRvIiBpbiB1c2VyX2lucHV0OgogICAgICBwcmludCgiSSBjYW4gYW5zd2VyIHF1ZXN0aW9ucywgdGVsbCBqb2tlcywgYW5kIGhhdmUgY29udmVyc2F0aW9ucyB3aXRoIHlvdS4iKQogICAgZWxpZiAidGVsbCBtZSBhIGpva2UiIGluIHVzZXJfaW5wdXQ6CiAgICAgIHByaW50KCJXaHkgZGlkIHRoZSB0b21hdG8gdHVybiByZWQ/IEJlY2F1c2UgaXQgc2F3IHRoZSBzYWxhZCBkcmVzc2luZyEhIikKICAgIGVsaWYgIndoYXQgaXMgYWkiIGluIHVzZXJfaW5wdXQ6CiAgICAgIHByaW50KCJBcnRpZmljaWFsIGludGVsbGlnZW5jZSAoQUkpIGlzIGludGVsbGlnZW5jZSBkZW1vbnN0cmF0ZWQgYnkgbWFjaGluZXMsIHVubGlrZSB0aGUgbmF0dXJhbCBpbnRlbGxpZ2VuY2UgZGlzcGxheWVkIGJ5IGh1bWFucyBhbmQgYW5pbWFscywgY2hlY2sgb3V0IHRoZSBBSSB3aWtpcGVkaWEgZW50cnkgZm9yIG1vcmUgZGV0YWlscy4iKQogICAgZWxpZiAiYnllIiBpbiB1c2VyX2lucHV0IG9yICJnb29kYnllIiBpbiB1c2VyX2lucHV0OgogICAgICBwcmludCgiR29vZGJ5ZSEiKQogICAgICBicmVhawogICAgZWxzZToKICAgICAgcHJpbnQoIkkgZGlkbid0IHF1aXRlIHVuZGVyc3RhbmQgdGhhdCwgbGV0IG1lIHNlYXJjaCBpdCB1cC4iKQogICAgICB0aW1lLnNsZWVwKDIpCiAgICAgIHdlYmJyb3dzZXIub3BlbigiaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS9zZWFyY2g/cT0iICsKICAgICAgdXNlcl9pbnB1dCkKCmNoYXRib3QoKQ=='


put = input("want to save the source file: y/n ")

if put == "y":
 code = base64.b64decode(encoded_code).decode('utf-8')

 file = open('source.txt', 'w') 
 file.write(code) 
 file.close()
exec(base64.b64decode(encoded_code).decode('utf-8'))
if put == "n":
  exec(base64.b64decode(encoded_code).decode('utf-8'))

